In [16]:
import pandas as pd
import numpy as np
import re

In [17]:
df_m=pd.read_csv(r"C:\Users\HP\Desktop\ducat jupyter\datasets\movies\movies.csv")
df_r=pd.read_csv(r"C:\Users\HP\Desktop\ducat jupyter\datasets\movies\ratings.csv")
df_t=pd.read_csv(r"C:\Users\HP\Desktop\ducat jupyter\datasets\movies\tags.csv")
df_l=pd.read_csv(r"C:\Users\HP\Desktop\ducat jupyter\datasets\movies\links.csv")
df_b=pd.read_csv(r"C:\Users\HP\Desktop\ducat jupyter\datasets\movies\boxoffice.csv")
df_me=pd.read_csv(r"C:\Users\HP\Desktop\ducat jupyter\datasets\movies\movies_metadata.csv")

C:\Users\HP\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [18]:
df1=pd.merge(df_m,df_r,on="movieId")

In [19]:
df2=pd.merge(df1,df_l,on="movieId")

In [20]:
df2=df2.drop("timestamp",axis=1)

In [23]:
df_me=df_me.drop("genres",axis=1)

In [24]:
#df2["year"]=df2.title.str.extract('([(]?[0-9]{4}[)])')
#df2["year"]=df2.title.str.extract('(\d{4})')

In [25]:
#df2["new_title"]=df2.title.str.extract('(\w+)')

In [26]:
df2[["title","year","c_n"]]= df2["title"].str.split('([(]?[0-9]{4}[)])',n=1,expand = True)
df2["year"]=df2.year.str.extract("(\d{4})")

In [27]:
df2['title']=df2.title.apply(lambda x :x[:-1])
df2=pd.merge(df_me,df2,on="title")

In [28]:
df2.drop(["c_n"],axis=1,inplace=True)

In [30]:
#x=df2["genres"].str.split("|",expand=True)

In [31]:
#df2.to_csv(r'C:\Users\HP\Desktop\ducat jupyter\datasets\movies\df2.csv')

In [32]:
temp=pd.merge(df2,df_b,on="title")

temp.genres=temp.genres.apply(lambda x:x.split("|"))

In [33]:
temp

,adult,belongs_to_collection,budget,homepage,id,imdb_id,original_language,original_title,overview,popularity,...,genres,userId,rating,imdbId,tmdbId,year_x,rank,studio,lifetime_gross,year_y
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,"[Adventure, Animation, Children, Comedy, Fantasy]",1,4.0,114709,862.0,1995,221,BV,191796233,1995
1,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,"[Adventure, Animation, Children, Comedy, Fantasy]",5,4.0,114709,862.0,1995,221,BV,191796233,1995
2,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,"[Adventure, Animation, Children, Comedy, Fantasy]",7,4.5,114709,862.0,1995,221,BV,191796233,1995
3,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,"[Adventure, Animation, Children, Comedy, Fantasy]",15,2.5,114709,862.0,1995,221,BV,191796233,1995
4,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.9469,...,"[Adventure, Animation, Children, Comedy, Fantasy]",17,4.5,114709,862.0,1995,221,BV,191796233,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75426,False,NaN,11000000,NaN,395834,tt5362988,en,Wind River,An FBI agent teams with the town's veteran gam...,40.796775,...,"[Action, Crime, Mystery, Thriller]",249,4.5,5362988,395834.0,2017,2461,Wein.,33800859,2017
75427,False,NaN,11000000,NaN,395834,tt5362988,en,Wind River,An FBI agent teams with the town's veteran gam...,40.796775,...,"[Action, Crime, Mystery, Thriller]",338,1.5,5362988,395834.0,2017,2461,Wein.,33800859,2017
75428,False,NaN,11000000,NaN,395834,tt5362988,en,Wind River,An FBI agent teams with the town's veteran gam...,40.796775,...,"[Action, Crime, Mystery, Thriller]",414,4.0,5362988,395834.0,2017,2461,Wein.,33800859,2017
75429,False,NaN,11000000,NaN,395834,tt5362988,en,Wind River,An FBI agent teams with the town's veteran gam...,40.796775,...,"[Action, Crime, Mystery, Thriller]",515,4.0,5362988,395834.0,2017,2461,Wein.,33800859,2017
75430,False,NaN,11000000,NaN,395834,tt5362988,en,Wind River,An FBI agent teams with the town's veteran gam...,40.796775,...,"[Action, Crime, Mystery, Thriller]",599,3.0,5362988,395834.0,2017,2461,Wein.,33800859,2017

In [34]:
df_mean=temp.groupby("title")["rating"].mean()
df_av_mean=temp.groupby("title")["vote_average"].mean()

In [62]:
df_s=temp[["movieId","studio","adult","vote_average","original_language"]]

In [65]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
studio=lb.fit_transform(df_s.studio)
adult=lb.fit_transform(temp.adult)
language=lb.fit_transform(temp.original_language)

In [66]:
'''studio=set()
for i in df_s.studio:
    studio.add(i)
df=pd.DataFrame(columns=studio,index=temp.title)
d=[]
for i in temp.studio:
    df_n=[]
    for j in df:
        if j in i:
            df_n.append(1)
        else:
            df_n.append(0)
    d.append(df_n)
dfs=pd.DataFrame(d,columns=studio,index=temp.movieId)

dfs["studio"]=x
dfs'''

'studio=set()\nfor i in df_s.studio:\n    studio.add(i)\ndf=pd.DataFrame(columns=studio,index=temp.title)\nd=[]\nfor i in temp.studio:\n    df_n=[]\n    for j in df:\n        if j in i:\n            df_n.append(1)\n        else:\n            df_n.append(0)\n    d.append(df_n)\ndfs=pd.DataFrame(d,columns=studio,index=temp.movieId)\n\ndfs["studio"]=x\ndfs'

In [67]:
genres=[]
for i in temp.genres:
    for j in i:
        if j not in genres:
            genres.append(j)
df=pd.DataFrame(columns=genres,index=temp.title)

In [98]:
d=[]
for i in temp.genres:
    df_n=[]
    for j in df:
        if j in i:
            df_n.append(1)
        else:
            df_n.append(0)
    d.append(df_n)
dft=pd.DataFrame(d,columns=genres,index=temp.title)
dft["studio"]=studio
dft["rating"]=df_mean
dft["vote_average"]=df_av_mean
dft["language"]=language
#dft["adult"]=adult

In [100]:
dft=dft.drop_duplicates()
dft

,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller,...,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed),studio,rating,vote_average,language
title,,,,,,,,,,,,,,,,,,,,,
Toy Story,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,37,3.920930,7.7,9
Jumanji,1,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,231,3.431818,6.9,9
Grumpier Old Men,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,268,3.259615,6.5,9
Waiting to Exhale,0,0,0,1,0,1,1,0,0,0,...,0,0,0,0,0,0,97,2.357143,6.1,9
Father of the Bride Part II,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,37,3.071429,5.7,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Valerian and the City of a Thousand Planets,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,218,2.875000,6.7,9
Atomic Blonde,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,96,3.000000,6.1,9
Good Time,0,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,3,3.000000,7.3,9
The Emoji Movie,0,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,231,0.500000,5.8,9
Wind River,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,273,3.400000,7.4,9

In [101]:

#x=df2.pivot(index="movieId",columns="userId",values="rating")

#x.fillna(0,inplace=True)


#x

In [102]:
#df_new=pd.merge(dft,dfs,on="movieId")

In [103]:
from sklearn.neighbors import NearestNeighbors
def movie(i):
    nn=NearestNeighbors()
    nn.fit(dft)
    d,index=nn.kneighbors(dft.loc[[i]],n_neighbors=10)
    for i , j in zip(d[0],index[0]):
        if(j==4):
            print(f"movie{dft.index[j]}")
        else:
            print(f"rec   {dft.index[j]}  with distance  {i}")
movie("Jumanji")

rec   Jumanji  with distance  0.0
rec   Fly Away Home  with distance  1.0494631034563124
rec   Cloudy with a Chance of Meatballs  with distance  1.7803158448491232
rec   Monster House  with distance  1.8608742636732591
rec   Stuart Little  with distance  1.8862028858091613
rec   Alaska  with distance  1.973486447972352
rec   Final Fantasy: The Spirits Within  with distance  2.001480911508035
rec   Seven Years in Tibet  with distance  2.002501071511985
rec   Hotel Transylvania  with distance  2.0026274064152867
rec   Some Mother's Son  with distance  2.0036588432990734